spring.application.name=OnlineAuction_Backend

server.port=8080

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/online_auction_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
spring.datasource.username=root
spring.datasource.password=nguyenhuytan2004
# spring.datasource.password=3333

# Allow origins
app.cors.allowed-origins=http://localhost:5173

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Hibernate Search Configuration
spring.jpa.properties.hibernate.search.backend.analysis.configurer=com.example.backend.config.SearchAnalyzerConfig
spring.jpa.properties.hibernate.search.backend.directory.root=./search-index
spring.jpa.properties.hibernate.search.backend.lucene_version=LATEST

# Validation Configuration
spring.jackson.deserialization.fail-on-unknown-properties=true

# Auto-renew Auction Configuration
auction.renew.trigger-duration=PT5M
auction.renew.extend-duration=PT10M

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Main Queues Configuration
rabbitmq.email.queue.name=email_queue
rabbitmq.email.exchange.name=email_exchange
rabbitmq.email.routing_key.name=email_routingKey

# Dead Letter Queues Configuration
rabbitmq.dlq.email.queue.name=dlq_email_queue
rabbitmq.dlq.email.exchange.name=dlq_email_exchange
rabbitmq.dlq.email.routing_key.name=dlq_email_routingKey

# RabbitMQ Listener Configuration (Multiple Consumers)
spring.rabbitmq.listener.simple.concurrency=2
spring.rabbitmq.listener.simple.prefetch=1

# RabbitMQ Retry Configuration
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=3000
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.multiplier=2

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

# JWT
app.jwt.secret=cf3fd9959444932ac5953ece66001a8a0a53b1ae01f8e13f126c8eae96930905
# 30 minutes
app.jwt.access-token-expiration-ms=1800000
# 7 days
app.jwt.refresh-token-expiration-ms=604800000

# VNpay config
vnpay.tmn-code=ELRWBB7C
vnpay.hash-secret=Z1F0BF8L5K7B7BFBM45VVSBP4WYX6ZJT
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=https://localhost:8080/payment/vnpay-return
vnpay.ipn-url=

# Momo Config
momo.endpoint=${MOMO_ENDPOINT}
momo.partnerCode=${MOMO_PARTNER_CODE}
momo.accessKey=${MOMO_ACCESS_KEY}
momo.secretKey=${MOMO_SECRET_KEY}
momo.redirectUrl=${MOMO_REDIRECT_URL}
momo.ipnUrl=${MOMO_IPN_URL}

# PayOS Config
payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}
payos.returnUrl=http://localhost:5173/payment-result
payos.cancelUrl=http://localhost:5173/payment/payos-cancel

#Capcha
recaptcha.secret-key=${RECAPTCHA_SECRET_KEY}
