spring.application.name=OnlineAuction_Backend

server.port=1402

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/online_auction_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=nguyenhuytan2004

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
# Giữ kết nối mở
spring.jpa.open-in-view=true
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Hibernate Search Configuration
spring.jpa.properties.hibernate.search.backend.analysis.configurer=com.example.backend.config.SearchAnalyzerConfig
spring.jpa.properties.hibernate.search.backend.directory.root=./search-index
spring.jpa.properties.hibernate.search.backend.lucene_version=LATEST

spring.jackson.deserialization.fail-on-unknown-properties=true