spring.application.name=OnlineAuction_Backend

server.port=1402

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/online_auction_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=nguyenhuytan2004

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.deserialization.fail-on-unknown-properties=true